const balls = [
    [
        {
            ball    :   '0',
            values  :   '0',
            display :   '.',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '1',
            values  :   '1',
            display :   '1',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '2',
            values  :   '2',
            display :   '2',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '3',
            values  :   '3',
            display :   '3',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '4',
            values  :   '4',
            display :   '4',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '5',
            values  :   '5',
            display :   '5',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   '6',
            values  :   '6',
            display :   '6',
            wicket  :   false,
            legal   :   true,
        },
    ],
    [
        {
            ball    :   'WD',
            values  :   '1',
            display :   'WD',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+1',
            values  :   '2',
            display :   'WD+1',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+2',
            values  :   '3',
            display :   'WD+2',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+3',
            values  :   '4',
            display :   'WD+3',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+4',
            values  :   '5',
            display :   'WD+4',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+5',
            values  :   '6',
            display :   'WD+5',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'WD+6',
            values  :   '7',
            display :   'WD+6',
            wicket  :   false,
            legal   :   false,
        },
    ],
    [
        {
            ball    :   'NB',
            values  :   '1',
            display :   'NB',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+1',
            values  :   '2',
            display :   'NB+1',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+2',
            values  :   '3',
            display :   'NB+2',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+3',
            values  :   '4',
            display :   'NB+3',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+4',
            values  :   '5',
            display :   'NB+4',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+5',
            values  :   '6',
            display :   'NB+5',
            wicket  :   false,
            legal   :   false,
        },
        {
            ball    :   'NB+6',
            values  :   '7',
            display :   'NB+6',
            wicket  :   false,
            legal   :   false,
        },
    ],
    [
        {
            ball    :   'LB+1',
            values  :   '1',
            display :   'LB+1',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'LB+2',
            values  :   '2',
            display :   'LB+2',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'LB+3',
            values  :   '3',
            display :   'LB+3',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'LB+4',
            values  :   '4',
            display :   'LB+4',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'LB+5',
            values  :   '5',
            display :   'LB+5',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'LB+6',
            values  :   '6',
            display :   'LB+6',
            wicket  :   false,
            legal   :   true,
        },
    ],
    [
        {
            ball    :   'B+1',
            values  :   '1',
            display :   'B+1',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'B+2',
            values  :   '2',
            display :   'B+2',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'B+3',
            values  :   '3',
            display :   'LB+3',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'B+4',
            values  :   '4',
            display :   'B+4',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'B+5',
            values  :   '5',
            display :   'B+5',
            wicket  :   false,
            legal   :   true,
        },
        {
            ball    :   'B+6',
            values  :   '6',
            display :   'B+6',
            wicket  :   false,
            legal   :   true,
        },
    ],

    [
        {
            ball    :   'W',
            values  :   '0',
            display :   'W',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+1',
            values  :   '1',
            display :   'W+1',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+2',
            values  :   '2',
            display :   'W+2',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+3',
            values  :   '3',
            display :   'W+3',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+4',
            values  :   '4',
            display :   'W+4',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+5',
            values  :   '5',
            display :   'W+5',
            wicket  :   true,
            legal   :   true,
        },
        {
            ball    :   'W+6',
            values  :   '6',
            display :   'W+6',
            wicket  :   true,
            legal   :   true,
        },
    ],
    [ 
       {
            ball    :   'W+WD',
            values  :   '1',
            display :   'W+WD',
            wicket  :   true,
            legal   :   false,
        },
        {
            ball    :   'W+NB',
            values  :   '1',
            display :   'W+NB',
            wicket  :   true,
            legal   :   false,
        },
    ],
    
];

export default balls;